spring:
  datasource:
    url: jdbc:mysql://8.142.155.84:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useSSL=false&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
   # static-locations: classpath:/public/upload/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8000

fileUpload:
  minSize: 1024
  maxSize: 5242880
  allowSuffix: jpg,png
  path: /src/main/resources/public
  dir: /upload/
